version: '2'
services:
  solr: 
    image: solr:6.3.0
    ports:
      - "8991:8983"
    volumes:
      - data-solr-dev:/opt/solr/server/solr/mycores/
      - ./spotlight_day_demo/solr/config:/opt/solr/server/solr/configsets/data_driven_schema_configs
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    environment: 
      - VERBOSE=yes
  dev:
    build:
      dockerfile: Dockerfile-dev #this is just the path to the dockerfile
      context: .
    volumes:
      - ./spotlight_day_demo:/spotlight_day_demo #host's approotpath:containerpath
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "3001:3001"
    links:
      - solr
    environment:
      - SOLR_URL=http://solr:8983/solr/mycore
      - OD_URL=http://128.223.85.55:3000
    entrypoint: /entrypoint.sh
volumes:
  data-solr-dev: {}
